### ISSUE TITLE
While the tree is deep, it raise http error 403

### ISSUE THREAD

**Issue by doekia** [mfbx9da4/git-sub-dir#1]
Hi,

Title says it all.

Traceback (most recent call last):
  File "../get_git_sub_dir.py", line 48, in <module>
    write_files(GITHUB_REPOS_API_BASE_URL + path, new_dir_name, recursive=recursive)
  File "../get_git_sub_dir.py", line 25, in write_files
    github_dir = json.loads(urllib2.urlopen(url).read())
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by mfbx9da4** [comment]
yeah this is due to rate limiting. limited to around 60 requests per hour. if you authenticate the app then it gives you 5000 but havent got around to that. http://developer.github.com/v3/#rate-limiting

**Comment by Hunter-Github** [comment]
@mfbx9da4 - you could have at least edited that piece of information into the README.
